### ISSUE TITLE
openrc-init telinit mount-ro

### ISSUE THREAD

**Issue by cromerc** [OpenRC/openrc#153]
I am having a problem running under openrc-init with my root partition during shutdown/reboot. The system can't remount my root partition as ro when the init script "mount-ro" is run which then causes the next boot to run an fsck to recover the partition because it was not unmounted properly. While using sysvinit I did what was suggested in this:
https://wiki.archlinux.org/index.php/OpenRC#During_shutdown_remounting_root_as_read-only_fails
So, I added "telinit u" after the sync line in mount-ro and the problem went away. However under openrc-init I can no longer do this since telinit is not supported.

Not sure what the best course of action would be here to fix this problem. Should openrc-init implement "telinit u"? Or is there some other underlying problem that needs to be fixed so that I won't even need telinit u?

My fstab looks like this:
```
# /dev/sda4
UUID=###	/         	ext4      	rw,noatime,data=ordered		0 1

# /dev/sda1
UUID=###     /boot     	vfat      	rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro		0 2

# /dev/sda6
UUID=###   /home  	ext4      	rw,noatime,data=ordered			0 2

# /dev/sda7
UUID=###	/data	ext4 rw,noatime,data=ordered		0 2

tmpfs	/tmp		tmpfs		nodev,nosuid			0 0
```

It successfully unmounts my home, boot, and data partition before it gets the root partition. But the root partition always fails.

**Comment by williamh** [comment]
This looks a lot like https://bugs.gentoo.org/show_bug.cgi?id=499662.
I haven't quite decided how I want to proceed either, because I would prefer to find a way in openrc-init to fix the issue. The concern about adding the telinit command is, if I do that, I would not have a way to know whether sysvinit is running, so I would have to always attempt to run that which would cause errors.
The equivalent of telinit u is "openrc-shutdown --reexec", so adding that could be a workaround, but again it will cause errors if you do that and switch back to sysvinit.

**Comment by cromerc** [comment]
I actually already tried using "openrc-shutdown --reexec". It does not work like telinit u. It actually causes the system to hang on shutdown and I have to force a poweroff by holding the power button.

As far as checking if openrc-init is the init currently running or not, how about write a /var/run/openrc/openrc-init file at boot. If that file exists it was booted under openrc-init. If not, then it is something else(runit, s6, or sysvinit). By creating that file at boot and checking for it during mount-ro you can avoid this bug in openrc-init at least. The problem would just be what to do for other init schemes like sysvinit, s6, runit, etc.

**Comment by williamh** [comment]
I would need to write this file to RC_SVCDIR, not /var/run/openrc, but I would still have something like this in mount-ro:

```
[ -e "${RC_SVCDIR}"/file ] && openrc-shutddown --reexec
```

So, I'm not sure that's the answer either.

**Comment by udeved** [comment]
Has there been any decision made yet?
Reason I ask, I was gonna split out the sysvinit compat(init, reboot,shutdown,halt,poweroff) to have a standalone sysvinit replacement package eg runit could use as well.

**Comment by udeved** [comment]
I did some testing with a split out sysv package, thought I'd share my findings.
openrc-shutdown and openrc-init both have depends on librc and libeinfo.
I think in order to make it work, pkgconfig would probably have to have a librc.pc entry instead of having the library with openrc.
For the moment, ts not feasible to proceed.

**Comment by cromerc** [comment]
This issue doesn't effect me anymore on my new laptop. I can't verify that it is still a problem. Going to close this.
