### ISSUE TITLE
Add an OpenRC state to provide information if services are crashed

### ISSUE THREAD

**Issue by mrueg** [OpenRC/openrc#223]
Currently there are no enums defined for a crashed service, which means every consumer of librc has to define what crashed means and check for it.

It would be great if there was another state that provides information about a service being crashed.
Alternatively, a rc_service_effective_state() function that does the crash check for you, would be appreciated. 

States are defined here:
https://github.com/OpenRC/openrc/blob/13ca79856e5836117e469c3edbcfd4bf47b6bab0/src/librc/rc.h.in#L175
rc_service_state:
https://github.com/OpenRC/openrc/blob/82da844b42ff83b2ebf944198e56ac2d81851897/src/librc/librc.c#L830

@williamh  @chutz

**Comment by dwfreed** [comment]
That's because there's no coherent meaning between supervisors.  start-stop-daemon only has crashed, whereas supervise-daemon has crashed and unsupervised (where the former means supervise-daemon crashed before starting the process to be supervised, and the latter means it crashed afterward; this check is implemented in shell).  There is `bool rc_service_daemons_crashed(char *service)` for checking whether a daemon has crashed; for start-stop-daemon, this means the daemon that was started no longer exists, and for supervise-daemon, it means the supervisor is gone.

**Comment by williamh** [comment]
@mrueg Did you check out using the rc_service_daemons_crashed() function? If you pass it a service name, it should return true or false based on whether or not the service you passed has a crashed daemon.

**Comment by williamh** [comment]
I will test having rc_service_state call that function and adding a CRASHED state if that is a better setup.

**Comment by williamh** [comment]
The following commits are related to this issue:

fa5aea80
0f4fa415
5d6dd97b
37e29442
4e0eace8

This will be included in OpenRC 0.36.
