### ISSUE TITLE
openrc-run --dry-run does not work in combination with --nodeps

### ISSUE THREAD

**Issue by jirutka** [OpenRC/openrc#224]
When I run e.g. `/etc/init.d/sshd --dry-run restart`, it does what’s promised, i.e. does not actually restart the service. However, when I add `--nodeps`, the service is restarted despite `--dry-run` specified!

**Comment by thiagowfx** [comment]
Should we check for `dry_run` before https://github.com/OpenRC/openrc/blob/301161a7a4bda27c7ebd54c537dfec0cbc926365/src/rc/openrc-run.c#L1059-L1066?

**Comment by martinetd** [comment]
I stumbled on a similar problem: running `rc-service xyz --nodeps restart` will also not flag the service as started if it wasn't started before!!
So you end up with a service that's completely unsupervised, not listed as active in rc-status, can't be restarted (claims the process already exists and fails starting again), not being stopped on shutdown. Great. (Found out because nodeps is enabled automatically when runlevel is still starting, and we have an hotplug service with a restart in udev which shows as non-starting if udev is early/normal startup is slow...)

Checking for dry_run explicitly would work for the problem above but wouldn't help with status tracking...
My gut feeling is that since svc_stop and svc_start honor nodeps we don't need this wart at all, I'll try to make a hanging reproducer without nodeps and add nodeps-without-this to check, and submit a patch with that example.
