### ISSUE TITLE
Possible removal of  the modules service on FreeBSD?

### ISSUE THREAD

**Issue by williamh** [OpenRC/openrc#233]
@pkgdemon and others:

I was researching the kldload command to see if there is something equivalent to the --first-time switch for modprobe on Linux for an issue I am working there [1].
Apparently the -n switch would do what I want.

In my research however, I found the info on loader.conf on FreeBSD [2], which I did not know about when I accepted pull request #91.

It looks to me like the preferred way to load modules on FreeBSD is loader.conf, and that works regardless of the boot scripts you are using.

If I am wrong, please correct me. Otherwise, I would like to propose removing the modules service from FreeBSD.

[1] https://bugs.gentoo.org/show_bug.cgi?id=659530
[2] https://www.freebsd.org/cgi/man.cgi?loader.conf(5)

**Comment by cromerc** [comment]
@williamh It might be wise to check with the guys at TrueOS as well. TrueOS is based on FreeBSD but they use OpenRC as the default init system.

**Comment by pkgdemon** [comment]
@williamh This will have no impact on TrueOS.  

We have our own init.d scripts for base:
https://github.com/trueos/trueos/tree/trueos-master/etc/init.d

With that said it is true that it can be problematic to load certain modules too early in loader.conf on stock FreeBSD.  It will often result in a kernel panic for ports modules like drm-next-kmod (drm 4.9), or nvidia-driver on legacy UEFI implementations.

Just according to word of mouth I believe the community proposal for FreeBSD to integrate OpenRC as an option for 12.0, or 13.0 is coming along.  I am not sure of it's exact status at the moment but if that happens I suspect they will also use standalone init.d scripts for base like we do for TrueOS.

**Comment by williamh** [comment]
@pkgdemon ok, thanks for the information. I'll probably keep it based on what you said about some modules being problematic to load early.

I an curious though, what are you doing differently in your base scripts, and what is going on with FreeBSD's base scripts?
I would be interested in working with both groups to integrate your base scripts into OpenRC if that is possible.

**Comment by pkgdemon** [comment]
@williamh Good question.  I know we have a handful at least 7 or 8 scripts the last I checked such as localmount, and some of which may have been modified to fix edge cases under TrueOS.  I can get that exact list if needed.  Other than the jails, and zfs services originated from pacbsd originally.  But I know jails in particular has been fixed to address all of the issues we encountered with it.  

I think most are conversions from FreeBSD rc.d scripts aside from that with maybe a few exceptions like cron.  In the beginning we were originally using the OpenRC version of network but we found years ago that it was easier to port network.subr to maintain compatibility.  We were finding things like building a lagg would lock up a system.  I don't fully recall but I know there were issues doing more advanced things like building a VLAN on FreeBSD at least in the sense of being able to follow the FreeBSD documentation to do so.  

Likewise we replaced bootmisc not to long ago with a dummy service that calls a more traditional cleanvar, and cleartmp which fixes the FreeBSD installer among other things with a traditional local service.  We now have a documentation difference in that our local service simply processes what is in /etc/rc.local the way FreeBSD does traditional vs backgrounding by default, and requiring separate scripts in the way Gentoo documentation suggests.  

These scripts especially network are unfortunately is not a drop in without these files modified to be sourced where needed as well:
https://github.com/trueos/trueos/blob/trueos-master/etc/network.subr
https://github.com/trueos/trueos/blob/trueos-master/etc/rc.subr

Also we modify devd.conf for it's service to call the correct config:
https://raw.githubusercontent.com/trueos/trueos/trueos-master/etc/devd.conf

So to make all of these base services work those files would just have to be stored somewhere, and the scripts would have to modified to source from the correct location.  

I think the plan for a FreeBSD patch is to make new files like:

/etc/openrc-devd.conf (modify service to use this conf instead of devd.conf)
/etc/openrc (instead of replacing rc.subr in the tree)
/etc/openrc.shutdown (instead of replacing rc.shtudown in the tree)
/etc/network-openrc.subr (instead of replacing network.subr in the tree)
/etc/openrc.subr ( instead of replacing rc.subr in the tree)

I suspect the patch will look very close to this:
https://github.com/rcbsd/freebsd/commit/67b3def0e8088dad7ddac362b6cddc6b68e28098

FreeBSD will not be pulling in dhcpcd, or that would have to be a separate proposed patch from my understanding.  Therefore the patch whether it is based on my effort or not I am not clear will be using dhclient instead.  We integrated dhcpcd for TrueOS into base, and that will remain our default.  Similarly LibreSSL will always be our default vs OpenSSL.

**Comment by williamh** [comment]
The modules service will not be removed since it is problematic to load some modules early.
@pkgdemon please stay in touch with me about the TtrueOS base scripts and the work going on on FreeBSD to accept OpenRC into the base system.

**Comment by pkgdemon** [comment]
@williamh Now that FreeBSD 12.0 has released we have begin the follow up from the [OpenRC working session at BSDcan](https://wiki.freebsd.org/DevSummit/201806/OpenRC).

@miwi-fbsd Has began the review process for import into master (13-CURRENT) https://reviews.freebsd.org/D18578

Once this is imported this will mean FreeBSD has OpenRC 0.35 and init scripts of it's own in base for modules.

**Comment by zoujiaqing** [comment]
thanks @pkgdemon @miwi-fbsd, how to status for it?
