### ISSUE TITLE
What is the minimal binaries to have it in place?

### ISSUE THREAD

**Issue by helioloureiro** [OpenRC/openrc#310]
Just a question.

I'm trying to adapt it to work into containers, but the current size is 88 MB (compiled statically).  Are there any binaries that I can remove in order to have a more lean size?

**Comment by williamh** [comment]
I've never thought about this, but if you want to test and let me know what works for you, I am interested.
Remember that we don't support statically linking PAM (I'm not sure what the reason for this is, but it has been unsupported since before I worked on OpenRC).
Also, remember that you can't be sure which binaries other service scripts outside of OpenRC will use, so you may break other service scripts by removing binaries.

**Comment by helioloureiro** [comment]
Thanks for the reply @williamh.  I noticed that /libexec/rc/sh/init.sh can be improved.  It has an variable mountproc=true that could be moved into /etc/rc.conf instead.
Because of that init.sh complains regarding missing binaries fstabinfo and mount, which aren't available in minimalistic containers.
