### ISSUE TITLE
bash-completion: rc-service auto completion fails when grep is aliased

### ISSUE THREAD

**Issue by Spyros-Ladon** [OpenRC/openrc#344]
Problem:
* `rc-service b<Tab>` fails to list services starting with 'b'.

Steps to reproduce:
* `alias grep='grep --color=always --line-number'`
* `rc-service b<Tab>`

**Comment by N-R-K** [comment]
Should be fixed by #597 

Also when looking at this I noticed this:

https://github.com/OpenRC/openrc/blob/ae5e38dce5bd7b30adb3131e7e76fab34a6f5c73/bash-completion/rc-service#L95-L101

I don't believe we should assume `extglob` to be unset - I think it's possible that some users have it set. Should we guard this under a condition so that if the user had `extglob` set it doesn't get unset by us? What do you think @williamh.
