### ISSUE TITLE
Make openrc-init play nicely with systemd-nspawn

### ISSUE THREAD

**Issue by LostGhost1** [OpenRC/openrc#410]
Systemd-nspawn can pass environment variables to /sbin/init (via "
-E --setenv=NAME=VALUE    Pass an environment variable toPID 1
"), now if openrc-init could read the "runlevel" variable and act accordingly...

**Comment by cromerc** [comment]
This makes no sense. systemd-nspawn requires that systemd-nspawn be installed on both the host and container chroot. It also requires that systemd be pid1 in the container.

If you have OpenRC installed then obviously systemd-nspawn is generally not present in the container.

Adding this is pointless and doesn't truly give systemd-nspawn support since it requires a running systemd container.

**Comment by LostGhost1** [comment]
I don't think systemd-nspawn is required inside the container. When the container is booted, /sbin/init (whatever it is) is executed as PID 1, and that's it. If you have evidence to the contrary, I would be glad to receive it.

**Comment by cromerc** [comment]
https://wiki.gentoo.org/wiki/Chroot#systemd-nspawn

https://wiki.archlinux.org/index.php/Systemd-nspawn#Create_a_Debian_or_Ubuntu_environment

They all say that both systemd and systemd-nspawn must be installed in thr container.

**Comment by LostGhost1** [comment]
Alright, fair enough, I guess that feature would be unnecessary
