### ISSUE TITLE
swclock saves time in tmpfs

### ISSUE THREAD

**Issue by cnoss74** [OpenRC/openrc#430]
swclock saves time in /var/run/openrc/shutdowntime, hard coded. /var/run is a symlink to /run, which is on tmpfs. No wonder it doesn't work. Maybe make the file an optional argument?

**Comment by williamh** [comment]
@cnoss74 The file can't be optional, because this file is used to save the shutdown time. You are correct however that this can't be saved on tmpfs.
The only other spot I can think of to save this file is in /var/lib/openrc/shutdowntime. However, that would require /var to be mounted in the initramfs or be on the same filesystem as / if you use swclock.
@vapier  Are these reasonable requirements in this situation?

**Comment by vapier** [comment]
swclock needs to have state somewhere. a path under /var makes the most sense.

**Comment by williamh** [comment]
I'm looking at this again along with the above proposed PR. I'm not comfortable with the PR because it changes the time on an executable.
My only concern about using /var is that will require us to wait until /var is mounted to fix the time.
Any thoughts anyone?

**Comment by dwfreed** [comment]
Fixed by #565
