### ISSUE TITLE
Need a way to indicate 'last' or 'near end' dependency.

### ISSUE THREAD

**Issue by oliv3r** [OpenRC/openrc#535]
Our embedded system, prints a nice banner (motd/issue) whenever it has completely finished booting. Right now, we use busybox init scripts for this, we do not have any getty or anything however. Using `S99final` in essence solves this (almost, as other services may be still starting in the background).

I am however unable to find a way to do this with openrc. E.g. there's no 'startup finished' dependency to hook into, or any way to say 'depend on everything'. Yes, the difficulty comes when multiple services want to be last, but there a before/after could help to identify this. Right now, the only way to do this, is to find out what is our final service that starts, and depend on that, which is a bit clunky, as if those dependencies change, this breaks. Also it codifies a dependency that does not exist.

**Comment by vapier** [comment]
this is somewhat by design ... a system that hotplugs is never truly "finished" booting.  services startup & shutdown all the time in reaction to events.

that said, you can probably accomplish what you want by simply dropping a script at `/etc/local.d/zzz-final.start` that prints whatever message you want.
