### ISSUE TITLE
Broken with >=ncurses-6.4_p20230408 (OpenRC abuses tparm API)

### ISSUE THREAD

**Issue by thesamesam** [OpenRC/openrc#619]
OpenRC is broken with >=sys-libs/ncurses-6.4_p20230408, like so:
```
openrc-0.46-build/src/einfo $ ./ewarn hi
 (null)*(null) hi(null)
```

This was originally reported in Gentoo at https://bugs.gentoo.org/904277. The ncurses maintainer, Thomas Dickey, provided some analysis (see the Gentoo bug for full details):
>I see that OpenRC is passing hardcoded strings to tgoto(),
>which do not come from the terminal database (when tgoto()
>returns a null, indicating a failure for that capability),
>and using the output of tgoto() to copy/use other places.
>
>That's a defect in OpenRC.  Perhaps they'll fix it.

OpenRC needs to use `tputs`, `printw`, etc instead of e.g. `printf` for strings obtained from ncurses.

Note that newer ncurses is needed to fix some security vulnerabilities (https://bugs.gentoo.org/904247), so there's some urgency to this.

**Comment by vapier** [comment]
i don't super care one way or the other

**Comment by deprecated-dot** [comment]
> i don't super care one way or the other

That's the spirit.

**Comment by bfrg** [comment]
I'm on Gentoo Linux and because of this "bug" I cannot install newer tmux version, since OpenRC requires the old ncurses version but that conflicts with the latest tmux. This is true for _every_ application that requires a newer ncurses. IMO something as essential as OpenRC should depend on ncurses.
