### ISSUE TITLE
output_logger and error_logger in supervise-daemon

### ISSUE THREAD

**Issue by phirecc** [OpenRC/openrc#644]
Is there a technical reason why the `{output,error}_logger` arguments are only available in start-stop-daemon but not in supervise-daemon? I'm not very familiar with the codebase but from my quick reading it looks like it could be implemented in a similar manner?

I would find it useful and some other users in https://github.com/OpenRC/openrc/issues/341 also seem to.

Thanks :)

**Comment by Higgs1** [comment]
I need this also, yes please!

Many need daemons to output to `syslog()` (because syslog is easily redirected to their choice of logger). This can easily be done with s-s-d by setting `{output,error}_logger=logger`. There is no reason that supervise-daemon shouldn't also allow this, and in my mind it's imperative that supervise-daemon has this feature also.

[In this comment](https://github.com/OpenRC/openrc/issues/118#issuecomment-299223810), it was said that "supervise-daemon is intended to be entirely analogous to start-stop-daemon with the exception that it monitors the child process, and restarts it if it exits." Currently this is not the case, as supervisor-daemon does not honour these variables.

Further write-up incoming (probably). Please wait a few minutes...

Thanks

**Comment by Higgs1** [comment]
I'm not confident in my ability to write a full PR, but I still want to investigate and share my findings. Maybe it will help someone who can write c but doesn't have the spoons to do the first few steps (which has been the case for me several times). If not, just delete this.

In [sh/start-stop-daemon.sh#L50-L51](https://github.com/OpenRC/openrc/blob/-/sh/start-stop-daemon.sh#L50-L51) it can be seen that the `{output,error}_logger` variables get passed to `start-stop-daemon` via command line options `--std{out,err}-logger`. [sh/supervise-daemon.sh](https://github.com/OpenRC/openrc/blob/-/sh/supervise-daemon.sh) is the equivalent file for `supervise-daemon`.

For s-s-d, the command line args get parsed in [src/start-stop-daemon/start-stop-daemon.c](https://github.com/OpenRC/openrc/blob/-/src/start-stop-daemon/start-stop-daemon.c) and assigned to the `stdout_process` variable. Most of the relevant code seems to be around [start-stop-daemon/start-stop-daemon.c#L1060-L1090](https://github.com/OpenRC/openrc/blob/-/src/start-stop-daemon/start-stop-daemon.c#L1060-L1090), which utilizes the `rc_pipe_command` function. This closely corresponds to `supervise-daemon` in [src/supervise-daemon/supervise-daemon.c#L542-L560](https://github.com/OpenRC/openrc/blob/-/src/supervise-daemon/supervise-daemon.c#L542-L560) (just without the "stdout_process" if branch).

Just looking at how the `std{out,err}_fd` variables are already implemented, it looks easy enough for me to make an attempt... and I can see if it works on my system... But I'm not sure how much that would help everyone. I'm very confident this feature will help lots of people though.

Thank you.

**Comment by N-R-K** [comment]
Seems to be fixed by #656, this issue should probably be closed.
