### ISSUE TITLE
fsck init script doesn't work with f2fs filesystem (and maybe btrfs?)

### ISSUE THREAD

**Issue by eNTi** [OpenRC/openrc#66]
``` 
* Checking local filesystems  ...
fsck.f2fs: invalid option -- 'p'
        Error: Unknown option ?

Usage: fsck.f2fs [options] device
[options]:
  -a check/fix potential corruption, reported by f2fs
  -d debug level [default:0]
  -f check/fix entire partition
  -t show directory tree [-d -1]
```

not sure how it behaves with btrfs but fsck.btrfs only says:
```
fsck.btrfs 
If you wish to check the consistency of a BTRFS filesystem or
repair a damaged filesystem, see btrfs(8) subcommand 'check'.
```

**Comment by ehegnes** [comment]
I was about to voice my complaints about this too, until I updated `f2fs-tools`. I'm running Gentoo, where `f2fs-tools` is stable at `1.4.1`. I updated to `1.6.0`, and the `-p (preen)` option has since been added to `fsck.f2fs`.

Although this issue does bring up the concern regarding the addition of newer fs checking to the init script. It seems unreasonable to force newer fs tools into using the `-a` and `-p` parameters. Would not it be better to check the fs type in `/etc/fstab` before executing a command to check and repair?

**Comment by williamh** [comment]
@eNTI @ehegnes: 
I have filed a stable request for f2fs-tools-1.6.0 [1]; this should take care of the issue for f2fs-tools.

/sbin/fsck, which is what the fsck service script runs,  is a front end to all of the filesystem checkers which are named /sbin/fsck.fstype. If you use fsck -A, which is the default for the fsck service script, the front end parses fstab, runs the correct filesystem checker for each file system, handles pass numbers from fstab, and makes sure not to run filesystem checks in parallel if the filesystems are on the same physical disk. Basically it handles all of the parallelization.

Unfortunately, if e2fsck (the file system checker for ext[234] filesystems) finds errors on a filesystem, the default is to prompt the user for what to do if -p, -n or -y are not specified on the command line. The -a option is a synonym for -p for historical reasons; I'm not sure if it is safe to remove it.

Because of the behavior of e2fsck, I have two choices:
I can either pass -a and -p to fsck -A or I can rewrite the service script to avoid using fsck -A.

If I pass -a and -p to fsck, they do get passed to the filesystem checkers. If the filesystem checkers error out instead of ignoring these options, this is a bug in the filesystem checkers. So, if fsck.btrfs is erroring out with -a or -p, it should be fixed there.

If I rewrite the service script, it would be a breaking change for our users, and I'm not sure it is worth the tradeoff. Basically, the service script would have to be multiplexed, then it would be up to you to set it up to parallelize properly.

Let me know your thoughts.

[1] https://bugs.gentoo.org/show_bug.cgi?id=577186

**Comment by williamh** [comment]
@eNTi:
I just found out more information about btrfs. fsck does not work at all with this file system type; checks are performed when it is mounted. If you need to repair a btrfs, there is a separate utility for this which should be  run manually.

**Comment by williamh** [comment]
I believe this issue is resolved. If not, feel free to comment and I'll re-open.
