### ISSUE TITLE
start-stop-daemon.sh: inconsistent service naming in the output

### ISSUE THREAD

**Issue by rindeal** [OpenRC/openrc#79]
`ebegin` lines in `ssd_{start,stop}` functions refer to the service by its `$name`, while `eend` lines by `$RC_SVCNAME`. `openrc-run` also uses `$RC_SVCNAME`.

Log then looks like this:
```plain
* Stopping ${name} ...
* start-stop-daemon: 1 process refused to stop
* Failed to stop ${RC_SVCNAME}                         [ !! ]
* ERROR: ${RC_SVCNAME} failed to stop
```

I'm not sure whether this is the intended behaviour, because in case where `$name` differs drastically, it may not be clear what was done.

**Comment by williamh** [comment]
The name variable is meant to be an optional name for the service that can override RC_SVCNAME for output purposes.

You are correct that $name is being used inconsistently in the supervisor scripts. However, openrc-run can't access this value because it is a shell variable.

I will fix the supervisor scripts to always refer to $name if it is set, then we can see how much confusion that generates.
